version: "3.7"
services:
  postgres-db:
    image: postgres:13
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbadm
      - POSTGRES_PASSWORD=p@ssw0rd
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
    volumes:
      - ./.pg_store:/var/lib/postgresql